#!/usr/bin/env bash
set -euo pipefail

# Candidate-bound release evidence. This script never creates a GitHub release;
# it only prepares, verifies, records, and finalizes a machine-readable
# candidate boundary consumed by the release workflow and preflight.

usage() {
  cat >&2 <<'USAGE'
Usage:
  scripts/release_candidate.sh prepare --boundary PATH [--tag TAG]
  scripts/release_candidate.sh verify --boundary PATH [--package PATH] [--fragments-dir PATH] [--archives-dir PATH] [--require-package] [--require-archives]
  scripts/release_candidate.sh record --boundary PATH --target TARGET --archive PATH --fragment PATH
  scripts/release_candidate.sh finalize --boundary PATH --package PATH --fragments-dir PATH --archives-dir PATH

The candidate boundary binds the tag, Cargo version, source/tree, lockfile,
toolchain, package contract, target matrix, and archive digests. All modes are
fail-closed and path-scoped; publication is only represented as a boundary
state and is never performed here.
USAGE
}

die() {
  printf 'release candidate: %s\n' "$1" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is required"
}

root="$(git rev-parse --show-toplevel)"
cd "$root"
require_command jq
require_command git
require_command cargo
require_command shasum

mode="${1:-}"
[[ -n "$mode" ]] || { usage; exit 2; }
shift
if [[ "$mode" == "--help" || "$mode" == "-h" ]]; then
  usage
  exit 0
fi

boundary=""
tag="${GITHUB_REF_NAME:-}"
fragments_dir=""
archives_dir=""
package_required=false
archives_required=false
package_override=""
target=""
archive=""
fragment=""

while (($# > 0)); do
  case "$1" in
    --boundary)
      (($# >= 2)) || { usage; exit 2; }
      boundary="$2"
      shift 2
      ;;
    --tag)
      (($# >= 2)) || { usage; exit 2; }
      tag="$2"
      shift 2
      ;;
    --fragments-dir)
      (($# >= 2)) || { usage; exit 2; }
      fragments_dir="$2"
      shift 2
      ;;
    --archives-dir)
      (($# >= 2)) || { usage; exit 2; }
      archives_dir="$2"
      shift 2
      ;;
    --require-package)
      package_required=true
      shift
      ;;
    --require-archives)
      archives_required=true
      shift
      ;;
    --package)
      (($# >= 2)) || { usage; exit 2; }
      package_override="$2"
      shift 2
      ;;
    --target)
      (($# >= 2)) || { usage; exit 2; }
      target="$2"
      shift 2
      ;;
    --archive)
      (($# >= 2)) || { usage; exit 2; }
      archive="$2"
      shift 2
      ;;
    --fragment)
      (($# >= 2)) || { usage; exit 2; }
      fragment="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

[[ -n "$boundary" ]] || die "--boundary is required"

sha256_file() {
  shasum -a 256 "$1" | awk '{print $1}'
}

bytes_file() {
  wc -c < "$1" | tr -d '[:space:]'
}

relative_to_root() {
  local file_path="$1"
  case "$file_path" in
    "$root"/*) printf '%s\n' "${file_path#"$root"/}" ;;
    *) printf '%s\n' "$file_path" ;;
  esac
}

resolve_path() {
  local file_path="$1"
  case "$file_path" in
    /*) printf '%s\n' "$file_path" ;;
    *) printf '%s/%s\n' "$root" "$file_path" ;;
  esac
}

metadata() {
  cargo metadata --locked --no-deps --format-version 1
}

package_version() {
  metadata | jq -r '.packages[0].version'
}

toolchain_channel() {
  sed -n 's/^[[:space:]]*channel[[:space:]]*=[[:space:]]*"\([^"]*\)".*$/\1/p' rust-toolchain.toml | head -n 1
}

target_matrix_json() {
  jq -n '["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]'
}

claim_scan_json() {
  local matches
  matches="$(git grep -n -I -E 'AI-generated|generated by AI|OpenAI-generated' -- . ':!scripts/release_candidate.sh' || true)"
  if [[ -n "$matches" ]]; then
    jq -n --arg matches "$matches" '{schema:"termiflow.ai_claim_scan.v1",status:"failed",method:"tracked-source-static-v1",findings:($matches | split("\n") | map(select(length > 0)))}'
  else
    jq -n '{schema:"termiflow.ai_claim_scan.v1",status:"passed",method:"tracked-source-static-v1",findings:[]}'
  fi
}

validate_tag_version() {
  local candidate_tag="$1"
  local version="$2"
  [[ "$candidate_tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "tag must be an exact vX.Y.Z value: $candidate_tag"
  [[ "${candidate_tag#v}" == "$version" ]] || die "tag $candidate_tag does not match Cargo version $version"
}

write_boundary() {
  local destination="$1"
  local document="$2"
  local parent
  parent="$(dirname -- "$destination")"
  mkdir -p "$parent"
  local staging
  staging="$(mktemp "${TMPDIR:-/tmp}/termiflow-release-boundary.XXXXXX")"
  printf '%s\n' "$document" > "$staging"
  if ! mv -f -- "$staging" "$destination"; then
    rm -f -- "$staging"
    return 1
  fi
}

load_boundary() {
  [[ -f "$boundary" ]] || die "boundary artifact not found: $boundary"
  jq empty "$boundary" >/dev/null 2>&1 || die "boundary is not valid JSON: $boundary"
  [[ "$(jq -r '.schema // ""' "$boundary")" == "termiflow.release_candidate.v1" ]] || die "boundary schema is invalid"
  [[ "$(jq -r '.version // 0' "$boundary")" == "1" ]] || die "boundary version is invalid"
}

verify_source_identity() {
  local require_clean="$1"
  local expected_sha expected_tree expected_lock expected_toolchain expected_channel
  expected_sha="$(jq -r '.candidate.sha // ""' "$boundary")"
  expected_tree="$(jq -r '.candidate.tree_sha // ""' "$boundary")"
  expected_lock="$(jq -r '.candidate.lock_sha256 // ""' "$boundary")"
  expected_toolchain="$(jq -r '.candidate.toolchain_sha256 // ""' "$boundary")"
  expected_channel="$(jq -r '.candidate.toolchain_channel // ""' "$boundary")"
  [[ "$expected_sha" == "$(git rev-parse HEAD)" ]] || die "HEAD does not match candidate source SHA"
  [[ "$expected_tree" == "$(git rev-parse HEAD^{tree})" ]] || die "tree does not match candidate tree SHA"
  [[ "$expected_lock" == "$(sha256_file Cargo.lock)" ]] || die "Cargo.lock does not match candidate digest"
  [[ "$expected_toolchain" == "$(sha256_file rust-toolchain.toml)" ]] || die "rust-toolchain.toml does not match candidate digest"
  [[ "$expected_channel" == "$(toolchain_channel)" ]] || die "toolchain channel does not match candidate"
  if [[ "$require_clean" == true && -n "$(git status --porcelain=v1)" ]]; then
    die "candidate checkout is dirty"
  fi
}

verify_package() {
  local require_file="$1"
  local package_path
  if [[ -n "$package_override" ]]; then
    package_path="$(resolve_path "$package_override")"
  else
    package_path="$(resolve_path "$(jq -r '.package.path // ""' "$boundary")")"
  fi
  if [[ ! -f "$package_path" ]]; then
    [[ "$require_file" == true ]] || return 0
    die "candidate package is missing: $package_path"
  fi
  [[ "$(sha256_file "$package_path")" == "$(jq -r '.package.sha256' "$boundary")" ]] || die "candidate package digest mismatch"
  [[ "$(bytes_file "$package_path")" == "$(jq -r '.package.bytes' "$boundary")" ]] || die "candidate package byte count mismatch"
}

verify_fragments() {
  local require_files="$1"
  [[ -n "$fragments_dir" ]] || {
    [[ "$require_files" == true ]] && die "--fragments-dir is required when archives are required"
    return 0
  }
  [[ -d "$fragments_dir" ]] || die "fragment directory is missing: $fragments_dir"
  local fragment_paths=()
  while IFS= read -r fragment_path; do
    fragment_paths+=("$fragment_path")
  done < <(find "$fragments_dir" -type f -name '*.json' -print | sort)
  [[ "${#fragment_paths[@]}" -gt 0 || "$require_files" != true ]] || die "no archive fragments found"
  local candidate_sha
  candidate_sha="$(jq -r '.candidate.sha' "$boundary")"
  local seen_targets='[]'
  local fragment_path fragment_target archive_name archive_path
  for fragment_path in "${fragment_paths[@]}"; do
    jq empty "$fragment_path" >/dev/null 2>&1 || die "malformed archive fragment: $fragment_path"
    [[ "$(jq -r '.schema // ""' "$fragment_path")" == "termiflow.release_archive_fragment.v1" ]] || die "archive fragment schema is invalid: $fragment_path"
    [[ "$(jq -r '.candidate_sha // ""' "$fragment_path")" == "$candidate_sha" ]] || die "archive fragment candidate SHA mismatch: $fragment_path"
    fragment_target="$(jq -r '.target // ""' "$fragment_path")"
    archive_name="$(jq -r '.archive // ""' "$fragment_path")"
    [[ -n "$fragment_target" && -n "$archive_name" ]] || die "archive fragment identity is incomplete: $fragment_path"
    [[ "$(jq --arg target "$fragment_target" '.candidate.targets | index($target) != null' "$boundary")" == true ]] || die "archive fragment target is outside candidate matrix: $fragment_target"
    [[ "$(jq --arg target "$fragment_target" --argjson seen "$seen_targets" '$seen | index($target) == null' <<< '{}')" == true ]] || die "duplicate archive fragment target: $fragment_target"
    seen_targets="$(jq --arg target "$fragment_target" '. + [$target]' <<< "$seen_targets")"
    if [[ -n "$archives_dir" ]]; then
      archive_path="$archives_dir/$archive_name"
      [[ -f "$archive_path" ]] || die "archive is missing for fragment $fragment_target: $archive_path"
      [[ "$(sha256_file "$archive_path")" == "$(jq -r '.sha256' "$fragment_path")" ]] || die "archive digest mismatch for $fragment_target"
      [[ "$(bytes_file "$archive_path")" == "$(jq -r '.bytes' "$fragment_path")" ]] || die "archive byte count mismatch for $fragment_target"
    fi
  done
  if [[ "$require_files" == true ]]; then
    local expected_count actual_count
    expected_count="$(jq '.candidate.targets | length' "$boundary")"
    actual_count="${#fragment_paths[@]}"
    [[ "$actual_count" == "$expected_count" ]] || die "archive fragment count $actual_count does not match target count $expected_count"
  fi
}

prepare() {
  [[ -n "$boundary" ]] || die "--boundary is required"
  local version candidate_tag source_sha tree_sha lock_sha toolchain_sha channel package_report package_path package_sha package_bytes
  version="$(package_version)"
  [[ -n "$tag" ]] || tag="v$version"
  candidate_tag="$tag"
  validate_tag_version "$candidate_tag" "$version"
  [[ -z "$(git status --porcelain=v1)" ]] || die "candidate checkout is dirty"
  source_sha="$(git rev-parse HEAD)"
  tree_sha="$(git rev-parse HEAD^{tree})"
  lock_sha="$(sha256_file Cargo.lock)"
  toolchain_sha="$(sha256_file rust-toolchain.toml)"
  channel="$(toolchain_channel)"
  [[ -n "$channel" ]] || die "rust-toolchain.toml has no channel"

  package_report="$(mktemp "${TMPDIR:-/tmp}/termiflow-package-report.XXXXXX")"
  trap 'rm -f -- "$package_report"' RETURN
  scripts/package_contract.sh --output "$package_report" >/dev/null
  package_path="$(resolve_path "$(jq -r '.crate' "$package_report")")"
  [[ -f "$package_path" ]] || die "package contract did not produce a crate: $package_path"
  package_sha="$(sha256_file "$package_path")"
  package_bytes="$(bytes_file "$package_path")"
  local claims
  claims="$(claim_scan_json)"
  local document
  document="$(jq -n \
    --arg schema 'termiflow.release_candidate.v1' \
    --arg tag "$candidate_tag" \
    --arg version "$version" \
    --arg sha "$source_sha" \
    --arg tree "$tree_sha" \
    --arg lock "$lock_sha" \
    --arg toolchain "$toolchain_sha" \
    --arg channel "$channel" \
    --arg package_path "$(relative_to_root "$package_path")" \
    --arg package_sha "$package_sha" \
    --argjson package_bytes "$package_bytes" \
    --argjson targets "$(target_matrix_json)" \
    --argjson claims "$claims" \
    '{schema:$schema,version:1,state:"candidate-ready",publication_allowed:false,prepared_at:(now|todateiso8601),candidate:{tag:$tag,version:$version,sha:$sha,tree_sha:$tree,lock_sha256:$lock,toolchain_channel:$channel,toolchain_sha256:$toolchain,targets:$targets,version_decision:"tag_matches_cargo_version"},package:{schema:"termiflow.package_contract.v1",path:$package_path,sha256:$package_sha,bytes:$package_bytes,extracted_all_targets:"passed",maintainer_sources:"excluded"},archives:[],archive_fragments:[],ai_claim_scan:$claims}')"
  write_boundary "$boundary" "$document"
  printf 'release candidate: prepared %s for %s\n' "$boundary" "$candidate_tag"
}

verify() {
  load_boundary
  verify_source_identity true
  local candidate_tag candidate_version
  candidate_tag="$(jq -r '.candidate.tag // ""' "$boundary")"
  candidate_version="$(jq -r '.candidate.version // ""' "$boundary")"
  validate_tag_version "$candidate_tag" "$candidate_version"
  if [[ -n "$tag" ]]; then
    [[ "$tag" == "$candidate_tag" ]] || die "requested tag $tag does not match candidate tag $candidate_tag"
  fi
  [[ "$(jq -r '.candidate.version_decision // ""' "$boundary")" == "tag_matches_cargo_version" ]] || die "candidate version decision is unresolved"
  [[ "$(jq -r '.ai_claim_scan.status // ""' "$boundary")" == "passed" ]] || die "AI/public-claims scan is not passed"
  [[ "$(jq -r '.package.extracted_all_targets // ""' "$boundary")" == "passed" ]] || die "package contract is not passed"
  verify_package "$package_required"
  verify_fragments "$archives_required"
  printf 'release candidate: verified %s\n' "$boundary"
}

record() {
  load_boundary
  [[ -n "$target" && -n "$archive" && -n "$fragment" ]] || die "record requires --target, --archive, and --fragment"
  [[ -f "$archive" ]] || die "archive is missing: $archive"
  [[ "$(jq --arg candidate_target "$target" '.candidate.targets | index($candidate_target) != null' "$boundary")" == true ]] || die "target is outside candidate matrix: $target"
  local archive_name candidate_sha document
  archive_name="$(basename -- "$archive")"
  candidate_sha="$(jq -r '.candidate.sha' "$boundary")"
  document="$(jq -n \
    --arg schema 'termiflow.release_archive_fragment.v1' \
    --arg candidate_sha "$candidate_sha" \
    --arg target "$target" \
    --arg archive "$archive_name" \
    --arg sha256 "$(sha256_file "$archive")" \
    --argjson bytes "$(bytes_file "$archive")" \
    '{schema:$schema,version:1,candidate_sha:$candidate_sha,target:$target,archive:$archive,sha256:$sha256,bytes:$bytes}')"
  write_boundary "$fragment" "$document"
  printf 'release candidate: recorded %s\n' "$fragment"
}

finalize() {
  [[ -n "$fragments_dir" && -n "$archives_dir" ]] || die "finalize requires --fragments-dir and --archives-dir"
  load_boundary
  verify_source_identity true
  verify_package true
  verify_fragments true
  local archive_records document
  archive_records="$(find "$fragments_dir" -type f -name '*.json' -print0 | xargs -0 -n 1 jq -c '{target,archive,sha256,bytes}' | jq -s 'sort_by(.target)')"
  document="$(jq \
    --argjson archives "$archive_records" \
    --arg state 'publication-ready' \
    --arg finalized_at "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" \
    '.state=$state | .publication_allowed=true | .finalized_at=$finalized_at | .archives=$archives | .archive_fragments=([ $archives[] | {target,archive,sha256,bytes} ])' "$boundary")"
  write_boundary "$boundary" "$document"
  printf 'release candidate: finalized %s\n' "$boundary"
}

case "$mode" in
  prepare) prepare ;;
  verify) verify ;;
  record) record ;;
  finalize) finalize ;;
  --help|-h) usage ;;
  *) usage; exit 2 ;;
esac
